# username = input('username: ')
# print('welcome username')
# print('welcome',username)
# print('welcome'+username)
# print('welcome',username,'!',sep='^-^')
# _ = 'haha'
# print(_)
if 3 > 0 :
    print('True')
    print('yes')
print('*' * 40)
if -0.0 :
    print('*' * 40)
print('*' * 40)

if '':
    print('true')
print('*' * 40)
if ' ':
    print('hello')
print('*' * 40)
if 88:
    print(88 ** 3)
print('*' * 40)
if ('bob'):
    print('who')
print('*' * 40)
# if [False] :
#     print('非空列表 true')
# print('*' * 40)
# print(divmod(5,3))
# pastport = {'name':'john','age':29,'sex':'male'}
# print(pastport)
# print(pastport['name'])
# print(pastport['age'])
# print(pastport['sex'])
# print('*' * 40)
# num_list = [1,2,4,16,16**2,128**2]
# print(num_list)
# print(num_list[-1])
# print(num_list[1]*num_list[2])
# print('*' * 40)
# name_list = ('john','tom','jack','lolita','bob','chihiyo','ansible','hadooper')
# print(name_list)
# print(name_list[0])
# print(name_list[1]+name_list[3])
# print(name_list[2]*2)
# print(name_list[3],name_list[5])
# print('*' * 40)
# print('hello world !')
# print('hello','world','!')
# print('hello'+'workd'+'!')
# print('''hello
# world
# !''')
# print('hello','world','!','hao',sep='***')
# print('123')
# print(123)
# print('123' + '123')
# print(123+123)
# print('#' * 40)
# print(7 * 2)
# print(7 ** 2)
# print(7 / 3)
# print(7 // 3)
# print(7-2)
# print(7%3)
# if 3 > 1:
#     print('ture')
# print('*' * 40)
# if 3 < 2:
#     print('true')
# print('$' * 50)
# if 3 > 1 or 5 > 9:
#     print('yes')
# print('(^-^)' * 20)
# if 3 > 1 and 5> 9:
#     print('yes')
# print('(\'&\')' * 20)
# if 3 != 1:
#     print('true')
# print(divmod(5,3))
#
# num = 123
# print(num)
# print(num + 2)
# print(num * 3)
# num = num + 27
# print(num % 2)
# print(num * 2)
# print(num - 2)
# print(num / 5)
# print(num // 7)
# print(num ** 2)
# print('(\'$\')' * 20)
# str = 'johnlee'
# print(str)
# print(str[0])
# print(str[3])
# print(str[-1])
# print(str[1:3])
# print(str[-1:-4])
# print(str[::2])
# print(str[::-1])
# print(str[::-2])
# print(str[1]+str[5])
print('(\'%\')' * 20)
alist = ['bob','john','lolita','lala','lucy','chihiyo',10]
print(alist)
print(len(alist))
print(alist[0])
print(alist[1])
print(alist[1]+alist[3])
alist[0] = 'jack'
print(alist[0])
alist.append('yaho')
print(alist[7])
print('(\'+\') * 20')
one = ('john','bob',10,20,'lucy')
print(one)
print(len(one))
print(one[0])
print(one[3])
print(one[2]+one[3])
print(one[0]+one[1])
print('*' * 40)
index = {'name':'john','age':29,'sex':'male','born':'GZ'}
print(index)
print(len(index))
print(index['name'])
print(index['age'])
print(index['name'],index['age'])
print(index['age'] * 2)
print('~(^--^)~' * 15)
