# from random  import  randint
# alist = [randint(1,100) for i in range(10)]
# print(alist)
# alist.append(10)
# print(alist)
# alist.insert(5, 22)
# print(alist)
# print(alist.index(10))
# alis.count(10)
# alist.reverse()
# alist.sort()
# alist.remove(1)
# alist.pop()

# blist = alist.copy()
# clist = alist

# alist.extend(clist)  
# alist.clear()  #清空

# from random import randint
# alist = [randint(1,100) for i in range(10)]
# print(alist)
# alist.append(10)
# print(alist)
# alist.insert(5, 10)
# print(alist)
# alist.sort()
# print(alist)
# alist.reverse()
# print(alist)
# alist.insert(5, 10)
# print(alist)
# alist.remove(10)
# print(alist)
# alist.pop()
# print(alist)
# alist.pop(-2)
# print(alist)
# blist = alist.copy()
# clist = alist
# print(alist)
# print(blist)
# print(clist)
# alist.pop()
# print(blist)
# print(alist)
# print(clist)
# alist.extend(clist)
# print(alist)
# alist.clear()
# print(alist)
# print(clist)
# print(blist)

atuple = (10, 22, 33, 234)
print(type(atuple))
aset = set([10, 20, 30])
print(type(aset))
print(aset)