# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-07 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webansi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Argulment',
            new_name='Argument',
        ),
    ]
